# Generated by Django 4.2.5 on 2023-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onvibes', '0002_comment_song_like_song_song_genres_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(db_column='artist_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(db_column='comment_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.TextField(db_column='genre_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='like_id',
            field=models.AutoField(db_column='like_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.AutoField(db_column='song_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
